---
name: Build RockPi 4C+

permissions:
  id-token: write
  contents: read
  pull-requests: write
  packages: write

on:
  workflow_dispatch:

jobs:
  build-armbian-rockpi4cplus:
    runs-on: ubuntu-latest
    steps:
      - uses: armbian/build@main
        with:
          armbian_token:     "${{ secrets.GITHUB_TOKEN }}"  # GitHub token
          armbian_release:   "jammy"                        # userspace
          armbian_target:    "build"                        # build=image, kernel=kernel
          armbian_board:     "rockpi-4cplus"                # build target